```{r}
library(ggplot2)
data(diamonds)
summary(diamonds)
```

```{r}
qplot(x = price, data = diamonds, bins = 200,
      color = I('black'), fill = I('green'))+
  scale_x_continuous(lim = c(0, 19000), breaks = seq(0, 19000, 5000))

```
```{r}
qplot(x = price, data = diamonds, bins = 100,
      color = I('black'), fill = I('green'))+
  scale_x_continuous(lim = c(0, 1500), breaks = seq(0, 1500, 500))
```
```{r}
## Histograms of diamond prices by cut.

qplot(x = price, data = diamonds, bins = 75,
      color = I('black'), fill = I('green'))+
  scale_x_continuous(lim = c(0, 19000), breaks = seq(0, 19000,5000))+
  facet_wrap(~diamonds$cut, scales = 'free_y')

```

by(diamonds$price, diamonds$cut, summary)

```{r}
## Histograms of price per carat

qplot(x = (carat / price) + 1, data = diamonds, bins = 100,
      color = I('Black'), fill = I('orange'))+
  scale_x_log10()+
  facet_wrap(~cut, scales = 'free')

```

```{r}
## Boxplotsof diamond prices vs clarity

qplot(y = price, x = clarity, data = diamonds,
      fill = clarity,
      main = 'Price vs. Clarity',
      geom = 'boxplot')+
  coord_cartesian(ylim = c(0, 7000))
```

```{r}
## Price per carat of diamonds vs. diamond colors

qplot(y = carat / price, x = color, data = diamonds,
      ylab = 'Price per carat', 
      fill = color,
      main = 'Price per carat vs. Color',
      geom = 'boxplot')+
  coord_cartesian(ylim = c(0, 0.0005))
```

```{r}
## Diamond weights(carat)

qplot(x = carat, data = diamonds, binwidth = 0.12,
            geom = 'freqpoly', color = color)

```

