library('ggplot2')
pf <- read.csv('pseudo_facebook.tsv', sep = '\t')
```{r}
qplot(y = friend_count, x = age, data = pf)
```


```{r}
ggplot(aes(age, friend_count), data = pf)+
  geom_point(alpha = 0.05, position = position_jitter(h = 0))+
  xlim(14, 90)+
  coord_trans(y = 'sqrt')
```

## Friendships initiated Vs. Age
```{r}
ggplot(aes(age, friendships_initiated), data = pf)+
  geom_point(alpha = 0.1, color = 'orange', position = position_jitter(h = 0))+
  xlim(13, 90)+
  coord_trans(y = 'sqrt')
```

```{r}
library('dplyr')
age_group <- group_by(pf, age)
pf.fc_by_age <- summarise(age_group,
                friend_count_mean = mean(friend_count),
                friend_count_median = median(friend_count),
                n = n())
pf.fc_by_age <- arrange(pf.fc_by_age, age)
head(pf.fc_by_age)

ggplot(aes(age), data = pf.fc_by_age)+
  geom_line(aes(y = friend_count_mean), color = 'blue')+
  geom_line(aes(y = friend_count_median), color = 'red')
```

```{r}
pf.fc_by_age2 <- pf %>% 
  group_by(age) %>%
  summarise(friend_count_mean = mean(friend_count),
            friend_count_median = median(friend_count),
            n = n()) %>%
  
  arrange(age)
head(pf.fc_by_age2)
```

```{r}
## Scatterplot of age vs friend count with the mean, 10%, 50%(median) and 90% quantile lines added.

ggplot(aes(age, friend_count), data = pf)+
  geom_point(alpha = 0.1, color = 'orange', position = position_jitter(h = 0))+
  coord_cartesian(xlim = c(13, 70), ylim = c(0, 1000))+
  geom_line(stat = 'summary', fun.y = mean, color = 'red')+
  geom_line(stat = 'summary', fun.y = quantile, color = 'blue',
            fun.args = list(probs = 0.5))+
  geom_line(stat = 'summary', fun.y = quantile, linetype = 2, color = 'blue',
            fun.args = list(probs = 0.9))+
  geom_line(stat = 'summary', fun.y = quantile, linetype = 2, color = 'blue',
            fun.args = list(probs = 0.1))
```

```{r}
## Correlation
with(subset(pf, pf$age <= 70), cor.test(age, friend_count))
```
```{r}
ggplot(aes(likes_received, www_likes_received), data = pf)+
  geom_point(alpha = 0.1, color = 'red')+
  coord_cartesian(ylim = c(0, 5000), xlim = c(0, 10000))+
  geom_smooth(method = 'lm', se = FALSE)

with(subset(pf, pf$www_likes_received < 5000), cor.test(likes_received, www_likes_received))
```

```{r}
install.packages('alr3')
library('alr3')
data(Mitchell)
?Mitchell
```
```{r}
ggplot(aes(Month, Temp), data = Mitchell)+
  geom_point(alpha = 0.5)+
  scale_x_continuous(breaks = c(0, 203, 12))
```
```{r}
cor.test(Mitchell$Month, Mitchell$Temp)

```
```{r}
library('energy')
dcor.ttest(Mitchell$Month, Mitchell$Temp)
```
```{r}
library(dplyr)
pf<- read.csv('pseudo_facebook.tsv', sep = '\t')

pf.fc_by_age2 <- pf %>%
  group_by(age) %>%
  summarise(friend_count_mean = mean(friend_count),
  friend_count_median = median(friend_count),
  n = n()) %>%
  arrange(age)

head(pf.fc_by_age2)
```
```{r}
pf$age_with_month <- pf$age + 1 - pf$dob_month/12

pf.fc_age_with_month <- pf %>%
  group_by(age_with_month)%>%
  summarise(friend_count_mean = mean(friend_count),
            frien_count_median = median(friend_count),
            n = n()) %>%
  arrange((age_with_month))
head(pf.fc_age_with_month)

```

```{r}
ggplot(aes(age_with_month, friend_count_mean), 
       data = subset(pf.fc_age_with_month, age_with_month < 71))+
         geom_line()
```

## __________________________________________________________________________

```{r}
ggplot(aes(x, price), data = diamonds, na.rm = TRUE)+
  geom_point(alpha = 0.5, color = 'green')+
  coord_cartesian(xlim = c(3, 10))
```
```{r}
## Correlations

cor.test(diamonds$price, diamonds$x)
cor.test(diamonds$price, diamonds$y)
cor.test(diamonds$price, diamonds$z)
```
```{r}
ggplot(aes(depth, price), data = diamonds)+
  geom_point(alpha = 0.5)+
  scale_x_continuous(breaks = seq(40, 80, 2))+
  geom_smooth(method = lm)

cor.test(diamonds$depth, diamonds$price)
```

```{r}
ggplot(aes(carat, price), data = subset(diamonds, price < quantile(price, 0.99)
       & carat < quantile(carat, 0.99)))+
  geom_point(alpha = 0.5)
```

```{r}
diamonds$volume <- with(diamonds, x*y*z)

ggplot(aes(volume, price), data = subset(diamonds, volume > 0 & volume < 800))+
  geom_point(alpha = 0.1, aes(color = clarity))

```

```{r}
diamondsByClarity <- diamonds %>%
  group_by(clarity) %>%
  summarise(mean_price = mean(price),
            median_price = median(price),
            min_price = min(price),
            max_price = max(price),
            n = n())

head(diamondsByClarity)
```


```{r}
## Bar Plots
library(gridExtra)

diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

byClarity <- ggplot(data = diamonds_mp_by_clarity, aes(clarity, mean_price))+
  geom_bar(stat = 'identity')

byColor <- ggplot(data = diamonds_mp_by_color, aes(color, mean_price))+
  geom_bar(stat = 'identity')

grid.arrange(byClarity, byColor)

```

